### ISSUE TITLE
Can't set attribute in simple property

### ISSUE THREAD

**Issue by lainisourgod** [justengel/dataclass_property#5]
In my usecase I want to have "calculated properties": they are computed based on values of other properties.

It means I don't need a setter for them, only getter.

Here is is the simplest property without setter, that raises AtrributeError. Why?

```python
from dataclass_property import asdict, dataclass
from rich.traceback import install

install(show_locals=True)


@dataclass
class Hello:
    @property
    def what(self) -> int:
        return 5


print(Hello())

```

<img width="876" alt="image" src="https://user-images.githubusercontent.com/24773652/144311612-1c452404-981c-4bbe-ae13-c53d2ae7e6bc.png">

**Comment by justengel** [comment]
Fixed in version 1.4.0. Properties without a setter (fset) will use init=False. Added your code as a test file test_read_only.py

**Comment by lainisourgod** [comment]
@justengel Thank you!

**Comment by lainisourgod** [comment]
Still not working for me in python 3.7 and 3.9

```python
Traceback (most recent call last):
  File "/Users/me/code/other/try-dataclass-property/here.py", line 5, in <module>
    class Hello:
  File "/Users/me/.local/miniconda3/envs/ttt/lib/python3.9/site-packages/dataclass_property/internals_old.py", line 53, in dataclass
    return wrap(cls)
  File "/Users/me/.local/miniconda3/envs/ttt/lib/python3.9/site-packages/dataclass_property/internals_old.py", line 45, in wrap
    return mcs._process_class(cls, init, repr, eq, order, unsafe_hash, frozen)
  File "/Users/me/.local/miniconda3/envs/ttt/lib/python3.9/site-packages/dataclass_property/internals_old.py", line 185, in _process_class
    cls_fields = [mcs._get_field(cls, name, type)    # <<<EDITED>>>
  File "/Users/me/.local/miniconda3/envs/ttt/lib/python3.9/site-packages/dataclass_property/internals_old.py", line 185, in <listcomp>
    cls_fields = [mcs._get_field(cls, name, type)    # <<<EDITED>>>
  File "/Users/me/.local/miniconda3/envs/ttt/lib/python3.9/site-packages/dataclass_property/internals_old.py", line 63, in _get_field
    f = mcs.make_field(cls, a_name)  # <<<EDITED>>>
  File "/Users/me/.local/miniconda3/envs/ttt/lib/python3.9/site-packages/dataclass_property/interface.py", line 88, in make_field
    f = mcs.field(default=default, **field_kwargs)
TypeError: field() got an unexpected keyword argument 'kw_only'
```

**Comment by justengel** [comment]
Looks like different versions of dataclasses takes different parameters in the field function. I updated the code to inspect the field function in order to find default values. Version 1.4.1 will hopefully work for you.
